/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        gray: {
          50: '#F7F6F6',
          100: '#EFEDF5',
          200: '#D7D4E2',
          300: '#B8B4C7',
          400: '#9994AC',
          500: '#7A7591',
          600: '#5C5775',
          700: '#3D3852',
          800: '#1F1B2E',
          900: '#120F1A',
        },
        pink: {
          light: '#FED7E2',
          hover: '#B83280',
          primary: '#D53F8C',
          400: '#B83280',
          500: '#D53F8C',
        },
        error: {
          hover: '#751025',
          primary: '#D12D50',
        },
        // Observability design system tokens (from mockups)
        'primary': '#ad1a6c',
        'primary-container': '#cd3886',
        'primary-fixed': '#ffd9e5',
        'primary-fixed-dim': '#ffb0cf',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#3d0023',
        'on-primary-fixed-variant': '#8c0055',
        'secondary': '#5d5c74',
        'secondary-container': '#e2e0fc',
        'secondary-fixed-dim': '#c6c4df',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#1a1a2e',
        'on-secondary-fixed-variant': '#45455b',
        'on-secondary-container': '#63627a',
        'tertiary': '#046c00',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#f8ffef',
        'surface': '#faf9f9',
        'surface-dim': '#dadada',
        'surface-container': '#eeeeee',
        'surface-container-low': '#f4f3f3',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e9e8e8',
        'surface-container-highest': '#e3e2e2',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#574149',
        'background': '#faf9f9',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f1f0f0',
        'outline': '#8a7079',
        'outline-variant': '#ddbfc8',
        'obs-error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
